version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo build Starting on 'date'
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commnds:
      - echo $(basename ./build/libs/*.jar)
      - pwd
cache:
  paths:
    # - '/root/.gradle/**/*' # 캐싱파일 용량이 300MB 되고 느리다
    - '/root/.gradle/caches/**/*' # 캐싱파일 용량이 70mb 되고 빠르다
artifacts:
  files: build/libs/*.jar
