version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Install phase"
  build:
    commands:
      - echo build Starting on 'date'
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commnds:
      - echo $(basename ./build/libs/*.jar)
      - pwd
cache:
  paths:
    - './aws-3tier-architecture/.gradle/**/*'
    - './dodo-development-bucket/cache/**/*'
artifacts:
  files: build/libs/*.jar
