spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://dodo-mysql-rds.cet6jusu056s.ap-northeast-1.rds.amazonaws.com:3306/dodo
    username: dodo
    password: anwkdrhdql
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      ddl-auto: update
    defer-datasource-initialization: true
  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    h2:
      console:
        enabled: true
server:
  port: 8080
  address: 0.0.0.0