spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
  redis:
    host: ${SSM_REDIS_ENDPOINT}
    port: 6379
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SSM_DB_ENDPOINT}
    username: ${SSM_DB_ID}
    password: ${SSM_DB_PW}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
      ddl-auto: update
    defer-datasource-initialization: true
  http:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
    h2:
      console:
        enabled: true
server:
  port: 8888
  address: 0.0.0.0
#datasource:
#  url: ${rds.url}?useSSL=false&readFromMasterWhenNoReplica=true
logging:
  level:
    org.springframework.data.redis.repository.support.RepositoryConfigurationExtensionSupport: ERROR

