version: 0.0
os: linux
files:
  - source:  /
    destination: /home/dodo_admin/
permissions:
  - object: /
    pattern: "**"
    owner: dodo_admin
    group: dodo
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: dodo_admin